name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: mattyhall
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop -c zig fmt --check .
    - run: nix develop -c zig build
    - run: nix develop -c zig build test
